### ISSUE TITLE
Latest Version Magento 2.2.6 Payfast Not working 

### ISSUE THREAD

**Issue by vrajeshpatel4u** [PayFast/mod-magento_2.x.x#1]
Hello,

I have recently installed Magento 2.2.6 latest version and installed Payfast from this github. When selecting Payment Method as Payfast It gives following error in console http://127.0.0.1/magento226/rest/default/V1/guest-carts/bgJXobu8FmT1wmPDluN5AX6qOnjRaCIr/payment-information 500 (Internal Server Error). I have attached the screenshot for your reference. 
![payfasterror](https://user-images.githubusercontent.com/40518060/46855475-72cbc680-ce21-11e8-8f3e-8cdcb086ed71.png)

**Comment by katrein** [comment]
Good day Vrajesh,

We would need to assist specifically with your installation.
Please submit your query to merchantsupport@payfast.co.za and we can follow up with you.

PayFast Support

**Comment by vrajeshpatel4u** [comment]
Thank You. I have submitted this issue to merchantsupport@payfast.co.za .
