### ISSUE TITLE
PayFast issue with Magento 2.3 when selected Capture Online

### ISSUE THREAD

**Issue by codemastering** [PayFast/mod-magento_2.x.x#2]
when i am trying to create invoice and selected the option "Capture Online" and click Submit Invoice than its giving below error

"The invoice can't be saved at this time. Please try again later."

When i checked the logs it shows below.

main.CRITICAL: Class Payfast\Payfast\\Gateway\Request\CaptureRequest does not exist {"exception":"[object] (ReflectionException(code: -1): Class Payfast\\Payfast\\\\Gateway\\Request\\CaptureRequest does not exist at /root/vendor/magento/framework/Code/Reader/ClassReader.php:19)"} []

Please FIX this issue soonest possible. its extremely urgent and critical!

We are using Magento 2.3 with PHP 7.1.x

Please respond soonest

thank you

**Comment by JGPage** [comment]
Thanks for reporting this issue. We will investigate the issue and will have it resolved as soon as possible. 

Unfortunately I can't provide any timelines at this stage.

**Comment by codemastering** [comment]
@JGPage Thank you for the reply. Please try for soonest resolution as we are unable to receive payments from online channel. Thank you.

**Comment by JGPage** [comment]
@codemastering Could you provide more feedback? How was this issue found? and is this after an upgrade or some such? Was there any testing prior?

**Comment by codemastering** [comment]
@JGPage we implemented on our dev environment and the module was working fine but we never tried to place an order and this was our mistake,  We simply implemented the module on production environment and once we receive order from client, the order went through smoothly but when we tried to generate the invoice, We receive error saying "The invoice can't be saved at this time. Please try again later."

When we check the logs, we found below.

main.CRITICAL: Class Payfast\Payfast\Gateway\Request\CaptureRequest does not exist {"exception":"[object] (ReflectionException(code: -1): Class Payfast\Payfast\\Gateway\Request\CaptureRequest does not exist at /root/vendor/magento/framework/Code/Reader/ClassReader.php:19)"} []

Our prod & dev environment is having below specs.

Magento 2.3
PHP 7.1

I think you need to retest this module in Magento 2.3 it might not compatible with Magento 2.3 and you need to make it compatible with Magento 2.3

Should you require any other information please let me know.

thank you

**Comment by lefu007** [comment]
Hi @codemastering,

Thank you for bringing this to our attention.
please download the latest module and run
./bin/magento setup:di:compile command

kindly advice if there is other issues, we appreciate your feedback.

Regards

**Comment by codemastering** [comment]
@lefu007 

The module still giving issues with Magento 2.3 as per PayFast support email which we received today.

Please make this module compatible with Magento 2.3 soonest possible. Thank you
